[_]
schema-version = "0.2"

[io.buildpacks]
include = [
  "package.json",
  "package-lock.json",
  "src/",
  "public/",
  "index.html",
  "vite.config.js",
  "tailwind.config.js",
  "postcss.config.js"
]

[[io.buildpacks.group]]
id = "paketo-buildpacks/nodejs"

[io.buildpacks.build.env]
BP_NODE_VERSION = "18.*"
BP_NPM_VERSION = "latest"
